[project]
name = "venv"
version = "0.1.0"
description = "Example project installing TD2"
readme = "README.md"

# TD2 requires python 3.9 <-> 3.13
requires-python = ">=3.9,<3.14"
dependencies = [

    # This is the required package
    "td2>=1.0.8",
]
